allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin('com.android.library') &&
                project.android.externalNativeBuild.cmake.path != null) {
            project.android.defaultConfig.externalNativeBuild.cmake {
                arguments "-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--build-id=none"
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
