/// Flutter icons SuspensionIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SuspensionIcons
///      fonts:
///       - asset: fonts/SuspensionIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SuspensionIcons {
  SuspensionIcons._();

  static const _kFontFam = 'SuspensionIcons';
  static const String? _kFontPkg = null;

  static const IconData fork = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shock = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
