// Flutter icons SuspensionIcons
// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class SuspensionIcons {
  SuspensionIcons._();

  static const _kFontFam = 'SuspensionIcons';
  static const String? _kFontPkg = null;

  static const IconData fork =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shock =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tyre =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
